name: Deploy ADF Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to ${{ github.ref == 'refs/heads/main' && 'Production' || 'Development' }}
    environment: ${{ github.ref == 'refs/heads/main' && 'prd' || 'dev' }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Debug Variable
      run: |
        echo "Resource Group: ${{ vars.AZURE_RG }}"

    - name: Validate ARM template not by group
      run: |
        az deployment validate \
          --location westus2 \
          --template-file arm-templates/ARMTemplateForFactory.json



    - name: Validate ARM Template
      run: |
        az deployment group validate \
          --resource-group ${{ vars.AZURE_RG }} \
          --template-file arm-templates/ARMTemplateForFactory.json

    - name: Deploy ARM Template
      if: github.event_name == 'push'
      run: |
        az deployment group create \
          --resource-group ${{ vars.AZURE_RG }} \
          --template-file arm-templates/ARMTemplateForFactory.json

    - name: Azure Logout
      run: |
        az logout
      if: always()